### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by whdckszxxx** [mroonga/homebrew-mroonga#15]
# Please follow the general troubleshooting steps first:

- Ran brew install mroonga --no-sandbox --use-homebrew-mariadb

### Bug reports

Error: Operation not permitted - /Users/chan/Library/Logs/Homebrew/mariadb/01.cmake

### Description

When I run brew install mroonga --use-homebrew-mariadb above error was emitted.

OS X version: 10.12.3(16D30)

**Comment by kou** [comment]
Did you really ran with `--no-sandbox`?

Please paste output in terminal like the following:

```console
% brew install ...
....
...ERROR...
...
```

**Comment by cosmo0920** [comment]
See also: https://github.com/clear-code/statistics/issues/48#issue-251528925

**Comment by kou** [comment]
It'll be fixed by `--no-sandbox`.
