### ISSUE TITLE
Cannot install mroonga

### ISSUE THREAD

**Issue by enrique-gracias** [mroonga/homebrew-mroonga#16]
```
brew install mroonga --use-homebrew-mysql

==> Installing mroonga from mroonga/mroonga
==> Downloading http://packages.groonga.org/source/mroonga/mroonga-7.04.tar.gz
Already downloaded: /Users/Username/Library/Caches/Homebrew/mroonga-7.04.tar.gz
==> Downloading https://cdn.mysql.com/Downloads/MySQL-5.7/mysql-boost-5.7.19.tar.gz
Already downloaded: /Users/Username/Library/Caches/Homebrew/mysql-5.7.19.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mysql/5.7.19 -DCMAKE_BUILD_TY
Error: Operation not permitted @ dir_s_mkdir - /Users/Username/Library/Logs/Homebrew/mysql
```

Homebrew MySQL (5.7.19)
OS X Yosemite (10.10.5)

I have tried installing on Mac OS High Sierra and it also failed. It was a different error.

```
Error: Operation not permitted @ rb_sysopen /Users/Username/Library/Logs/Homebrew/mysql/cmake.01
```

**Comment by cosmo0920** [comment]
Duplicated with #15?

**Comment by enrique-gracias** [comment]
Any updates on this issue?

**Comment by kou** [comment]
Please try `brew install mroonga --use-homebrew-mysql --no-sandbox` and report the result.

**Comment by cosmo0920** [comment]
Should we add document to specify `--no-sandbox` like as https://github.com/Microsoft/msphpsql/blob/dev/README.md#step-2-install-prerequisites?

**Comment by cosmo0920** [comment]
@enrique-gracias I'd registered a PR to prevent "Operation not permitted" error. Could you try [installation commands which is preferable for you](https://github.com/mroonga/homebrew-mroonga/blob/7297300d479cf95af72f61ebdab7405f92a1af2a/README.md#the-homebrew-formula-for-mroonga)?

**Comment by enrique-gracias** [comment]
@cosmo0920 @kou Thank you! It worked!
