### ISSUE TITLE
Cannot tap mroonga/mroonga: invalid syntax in tap!

### ISSUE THREAD

**Issue by cu0ngnm** [mroonga/homebrew-mroonga#21]
When I run `brew tap mroonga/mroonga` below error was emitted.

> Cloning into '/usr/local/Homebrew/Library/Taps/mroonga/homebrew-mroonga'...
remote: Enumerating objects: 412, done.
remote: Total 412 (delta 0), reused 0 (delta 0), pack-reused 412
Receiving objects: 100% (412/412), 81.92 KiB | 665.00 KiB/s, done.
Resolving deltas: 100% (154/154), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/mroonga/homebrew-mroonga/mroonga.rb
mroonga: private method `include?' called for #<BuildOptions:0x00007faf6c8cb8b0>
Error: Cannot tap mroonga/mroonga: invalid syntax in tap!

I've tried looking for similar errors but nothing seems to be the same.
macOS Version: 11.5.1

**Comment by kou** [comment]
This isn't maintained.
Could you look into this issue and open a pull request?

**Comment by cu0ngnm** [comment]
I'm sorry but this issue is out of my knowledge 🙁

**Comment by kou** [comment]
I've updated.

Try the followings:

```console
$ brew tap mroonga/mroonga
$ brew install mroonga --with-homebrew-mysql --head
$ mysqld --daemonize
$ mysql -u root < $(brew --prefix)/share/mroonga/install.sql
```

See also: https://github.com/mroonga/homebrew-mroonga/blob/master/README.md
